apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-namespace-creator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: ["appstudio.redhat.com"]
  resources: ["components", "applications"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-namespace-creator-binding
subjects:
- kind: ServiceAccount
  name: appstudio-pipeline
  namespace: user-ns1
roleRef:
  kind: ClusterRole
  name: pipeline-namespace-creator
  apiGroup: rbac.authorization.k8s.io
