apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-deployer-binding
  namespace: user-ns1
subjects:
- kind: ServiceAccount
  name: appstudio-pipeline
  namespace: user-ns1
roleRef:
  kind: Role
  name: pipeline-deployer
  apiGroup: rbac.authorization.k8s.io

