apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-deployer
  namespace: user-ns1
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: ["appstudio.redhat.com"]
  resources: ["components", "applications"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["namespaces","services"]
  verbs: ["get", "create", "update", "delete"]
